### PR TITLE
Fix error in the example

### PR DESCRIPTION
**Pull request by luxiangzh**

### CODE REVIEW

**Comment by xavierholt** [comment]
I disagree with this.  Column numbers start at one, so the first decimal point is in column 8, and the second decimal point is in column 9.  There's nothing necessarily wrong with the first decimal point (if the text had been `7.8` instead of `7..8` it would be perfectly fine), so I don't think it makes sense to report an error there.  It's when you hit the second decimal point that you know something must be wrong, so that's where I'd expect the error to be.

**Comment by xavierholt** [comment]
Whoops - I focused on the wrong syntax error in my previous reply.  Sorry for the confusion!

I'd say the same logic applies here, though.  There's nothing necessarily wrong with the decimal in `50.` - the real problem is when the character that follows it (the newline) isn't a digit.

**Comment by luxiangzh** [comment]
I see. So are we intending to report the next column of this decimal point, which is not following with any numbers? cuz if someone makes a typo, and we report the next column instead of the column number of that specific decimal point, it could be confusing.

**Comment by xavierholt** [comment]
Yes - just report the next column as the location of the error.  If we were writing a calculator for release to the public we'd have better error messages (something like `Syntax error on line 1 column 9: expected digit, but found newline.`).  But I'd have to write a _lot_ of specification to make everybody's messages match, so I chose to only use line and column numbers.

In general, it's the first unexpected character that's the error:

```
1 2 3 4.
        ^
1.2.3 4
   ^
1 2 .3 4
    ^
```

**Comment by luxiangzh** [comment]
Understood. 

In my interpretation, when encountering a solitary decimal point without any subsequent decimals, the decimal point itself is considered the error as there shouldn't be a decimal point at the end of any number. However, in your interpretation, the absence of digits in the decimal point's following column is regarded as the error. Both are valid, but we will follow your instructions. 

Thank you!

**Pull request closed without merging**
